---
# tasks file for roles/rundeck
- name: Update Repositories
  become: yes
  apt:
    update_cache: yes

- name: Install Packages
  become: yes
  apt:
    name: "{{ packages }}"
  ignore_errors: "{{ ansible_check_mode }}"
  vars:
    packages:
      - openjdk-8-jdk-headless

- name: Add rundeck repo to sources.list
  become: yes
  shell: echo "deb https://rundeck.bintray.com/rundeck-deb /" | sudo tee -a /etc/apt/sources.list.d/rundeck.list

- name: Add rundeck repo gpg key
  become: yes
  shell: curl 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray' | sudo apt-key add -

- name: Update Repositories
  become: yes
  apt:
    update_cache: yes

- name: Install Rundeck
  become: yes
  apt:
    name: "{{ packages }}"
  ignore_errors: "{{ ansible_check_mode }}"
  vars:
    packages:
      - rundeck
      - rundeck-cli

- name: Enable rundeckd service and ensure it is not masked
  become: yes
  systemd:
    name: rundeckd
    enabled: yes
    masked: no

- name: Make sure rundeckd service is running
  become: yes
  systemd:
    state: started
    name: rundeckd
